import { NextRequest, NextResponse } from 'next/server';
import { query } from '@/lib/db';

import { error as logError, warn as logWarn, info as logInfo } from '@/lib/logger';

export const dynamic = 'force-dynamic';

/**
 * Database row type for products query. Sourced from the `products_unified`
 * view (migration 036) so vendor_products + the legacy `products` table
 * are UNION'd at the DB layer instead of needing two parallel queries.
 *
 * The view exposes `vendor_id`, `vendor_slug`, `vendor_name`,
 * `track_stock`, and `source` (`vendor_products` | `products`) so the
 * storefront can render provenance UI without a second round-trip.
 */
interface ProductRow {
  id: string;
  category_id: string;
  name_ar: string;
  name_en: string | null;
  sku: string | null;
  description: string | null;
  description_en: string | null;
  image_url: string | null;
  images: string[] | null;
  price: number | string;
  discount_price: number | string | null;
  stock_qty: number;
  is_active: boolean;
  track_stock: boolean;
  sort_order: number;
  source: 'vendor_products' | 'products';
  vendor_id: string | null;
  vendor_slug: string | null;
  vendor_name: string | null;
  category_id_ref: string;
  category_name: string | null;
  category_slug: string | null;
  category_icon: string | null;
  // Aggregated review stats from the LEFT JOIN in the products query —
  // `COALESCE`d to 0 in SQL so the row always has these fields, even
  // for products with no reviews yet.
  avg_rating: number | string;
  reviews_count: number | string;
  // Active offer (Slice 5). Populated by reading from
  // `products_unified_with_offers` instead of `products_unified` so the
  // storefront gets the winning offer without a second round-trip.
  // All nullable — most products will not be on an active offer.
  active_offer_id: string | null;
  active_offer_title_ar: string | null;
  active_offer_type: 'percentage' | 'fixed' | null;
  active_offer_value: number | string | null;
  active_offer_max_discount: number | string | null;
  active_offer_min_order: number | string | null;
  active_offer_starts_at: string | null;
  active_offer_ends_at: string | null;
}

/** Round to 2 decimals, mirroring offers.ts + DB NUMERIC(10,2) precision. */
function r2(n: number): number {
  return Math.round(n * 100) / 100;
}

/**
 * Convert products to Markdown table format
 */
function productsToMarkdown(products: any[], pagination: any): string {
  let md = '# Products Catalog\n\n';
  md += `> Total products: ${pagination.total} | Page ${pagination.page} of ${pagination.totalPages}\n\n`;

  md += '## Product List\n\n';
  md += '| ID | Name (AR) | Name (EN) | Vendor | Price | Discount | Stock | Category |\n';
  md += '|---|---|---|---|---|---|---|---|\n';

  for (const p of products) {
    const name = p.name_en ? `${p.name_ar} (${p.name_en})` : p.name_ar;
    const price = p.discount_price
      ? `~~${p.price}~~ **${p.discount_price}**`
      : p.price.toString();
    md += `| ${p.id.slice(0, 8)} | ${p.name_ar} | ${p.name_en || '-'} | ${p.vendor_name || '-'} | ${price} SAR | ${p.discount_price ? '✓' : '-'} | ${p.stock_qty} | ${p.category_name || '-'} |\n`;
  }

  md += '\n---\n';
  md += '*Generated by City Markets API*\n';

  return md;
}

/**
 * Check if client accepts markdown
 */
function acceptsMarkdown(request: NextRequest): boolean {
  const accept = request.headers.get('accept') || '';
  return accept.includes('text/markdown');
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const category = searchParams.get('category');
    const featured = searchParams.get('featured');
    const deals = searchParams.get('deals');
    // Slice 5: `on_offer=true` filters to products carrying any active offer;
    // `offer=<id>` narrows to products the given offer actually touches.
    const onOffer = searchParams.get('on_offer');
    const offerId = searchParams.get('offer');
    const search = searchParams.get('search');
    const sort = searchParams.get('sort');
    const minPrice = searchParams.get('minPrice') || searchParams.get('min_price');
    const maxPrice = searchParams.get('maxPrice') || searchParams.get('max_price');
    const inStock = searchParams.get('inStock');
    const vendorSlug = searchParams.get('vendor');
    const includeChildren = searchParams.get('include_children') === '1' || searchParams.get('includeChildren') === '1';
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '50');
    const offset = (page - 1) * limit;

    // Build WHERE clause and params.
    //
    // Slice 1: query the products_unified view (migration 036) instead of
    // `products` directly. The view UNION's `vendor_products` (active
    // listings) with legacy `products` rows not yet backfilled, with
    // vendor_id/vendor_slug/vendor_name surfaced so the storefront can
    // display provenance UI. We also LEFT JOIN `vendors` here to filter
    // out products whose vendor was deactivated — the view alone only
    // checks `vendor_products.is_active`, not the vendor's lifecycle.
    const conditions: string[] = ['(p.is_active IS NULL OR p.is_active = true)'];
    const params: (string | number)[] = [];

    if (category) {
      if (includeChildren) {
        // Recursive CTE: pull the category and all descendants, depth up to 3 in production.
        params.push(category);
        conditions.push(`c.id IN (
          WITH RECURSIVE tree AS (
            SELECT id FROM categories WHERE slug = $${params.length} AND is_active = TRUE
            UNION ALL
            SELECT ch.id FROM categories ch
            JOIN tree t ON ch.parent_id = t.id
            WHERE ch.is_active = TRUE
          )
          SELECT id FROM tree
        )`);
      } else {
        params.push(category);
        conditions.push(`c.slug = $${params.length}`);
      }
    }
    if (featured === 'true') {
      // `products_unified` doesn't expose `is_featured` — use `sort_order`
      // > 0 as the closest equivalent so the "featured products" surface
      // on the home page keeps returning rows.
      conditions.push('p.sort_order > 0');
    }
    if (deals === 'true') {
      conditions.push('p.discount_price IS NOT NULL AND CAST(p.discount_price AS DECIMAL) < CAST(p.price AS DECIMAL)');
    }
    // Active-offer filters. When `offer=<id>` is supplied we narrow by the
    // exact offer id (cross-checking scope via offer_targets). When only
    // `on_offer=true` is supplied we accept any in-window, active offer.
    if (offerId) {
      params.push(offerId);
      conditions.push(`EXISTS (
        SELECT 1 FROM offer_targets ot
        JOIN offers o ON o.id = ot.offer_id
        WHERE ot.offer_id = $${params.length}
          AND o.is_active = TRUE
          AND NOW() BETWEEN o.starts_at AND o.ends_at
          AND (
               (ot.target_type = 'product'  AND ot.target_id = p.id)
            OR (ot.target_type = 'category' AND ot.target_id = p.category_id)
            OR (ot.target_type = 'vendor'   AND ot.target_id = p.vendor_id)
            OR (ot.target_type = 'all')
          )
      )`);
    } else if (onOffer === 'true' || onOffer === '1') {
      conditions.push(`p.active_offer_id IS NOT NULL`);
    }
    if (search && search.trim()) {
      // Multi-token, multi-field search.
      // Splits the query on whitespace and matches ANY token in ANY of the
      // searchable fields (name_ar, name_en, description, description_en,
      // category_name, vendor_name). Empty tokens are skipped, so a query
      // like "لحوم  طازجة" with double spaces still works.
      //
      // Why OR across fields: for Arabic product discovery, the user's intent
      // is usually "any product related to X" rather than "product whose name
      // literally contains the full query". Searching `name_ar + name_en +
      // description + category_name + vendor_name` finds both the obvious
      // hit ("لحم بقري طازج" matches "لحوم") and the broader intent match
      // (a product in the "لحوم" category whose description says "طازج").
      //
      // Token-param is reused in ORDER BY for relevance scoring (products
      // with the full phrase in name_ar rank first).
      const searchTrimmed = search.trim();
      params.push(searchTrimmed);
      const searchParamIdx = params.length;
      conditions.push(`EXISTS (
        SELECT 1 FROM unnest(string_to_array($${searchParamIdx}, ' ')) AS token
        WHERE token <> '' AND (
             LOWER(p.name_ar)        LIKE '%' || LOWER(token) || '%'
          OR LOWER(COALESCE(p.name_en, ''))        LIKE '%' || LOWER(token) || '%'
          OR LOWER(COALESCE(p.description, ''))    LIKE '%' || LOWER(token) || '%'
          OR LOWER(COALESCE(p.description_en, '')) LIKE '%' || LOWER(token) || '%'
          OR LOWER(COALESCE(c.name_ar, ''))        LIKE '%' || LOWER(token) || '%'
          OR LOWER(COALESCE(v.name_ar, ''))        LIKE '%' || LOWER(token) || '%'
        )
      )`);
    }
    if (inStock === 'true' || inStock === '1') {
      // Honour `track_stock` for vendor rows — vendors opt out of stock
      // tracking for items they replenish continuously (bread, fresh
      // produce). The view surfaces `track_stock` so we can branch on
      // it here without JOIN'ing vendor_settings separately.
      conditions.push('(p.track_stock = false OR p.stock_qty > 0)');
    }
    if (vendorSlug) {
      params.push(vendorSlug);
      conditions.push(`v.slug = $${params.length}`);
    }

    if (minPrice) {
      const v = Number(minPrice);
      if (Number.isFinite(v) && v >= 0) {
        params.push(v);
        conditions.push(`COALESCE(p.discount_price, p.price) >= $${params.length}`);
      }
    }
    if (maxPrice) {
      const v = Number(maxPrice);
      if (Number.isFinite(v) && v > 0) {
        params.push(v);
        conditions.push(`COALESCE(p.discount_price, p.price) <= $${params.length}`);
      }
    }

    const whereSQL = conditions.length > 0 ? 'WHERE ' + conditions.join(' AND ') : '';

    // Get total count
    const countResult = await query(
      `SELECT COUNT(*) as total
         FROM products_unified_with_offers p
         LEFT JOIN categories c ON p.category_id = c.id
         LEFT JOIN vendors v ON v.id = p.vendor_id AND v.is_active = TRUE
         ${whereSQL}`,
      [...params]
    );
    const total = parseInt(countResult.rows[0].total);

    // Build ORDER BY
    let orderSQL = 'p.sort_order DESC, p.name_ar ASC';
    if (sort === 'price-asc') orderSQL = 'COALESCE(p.discount_price, p.price) ASC';
    else if (sort === 'price-desc') orderSQL = 'COALESCE(p.discount_price, p.price) DESC';
    else if (sort === 'newest') orderSQL = 'p.sort_order DESC, p.name_ar ASC';
    else if (sort === 'discount') orderSQL = 'p.active_offer_id IS NULL, (CAST(p.price AS DECIMAL) - COALESCE(CAST(p.discount_price AS DECIMAL), CAST(p.price AS DECIMAL))) DESC';

    // When a search query is active and the user didn't pick a sort, rank
    // by relevance so the products that match the query best show first:
    //   1. products with the *full phrase* in name_ar (best)
    //   2. products with *any token* in name_ar
    //   3. products with *any token* in name_en
    //   4. everything else (already filtered to match at least one token)
    if (search && search.trim() && !sort) {
      const searchTrimmed = search.trim();
      params.push(searchTrimmed);
      const searchParamIdx = params.length;
      const phrase = `LOWER('%' || LOWER($${searchParamIdx}) || '%')`;
      orderSQL = `
        (CASE
          WHEN LOWER(p.name_ar) LIKE ${phrase} THEN 0
          WHEN EXISTS (
            SELECT 1 FROM unnest(string_to_array($${searchParamIdx}, ' ')) AS token
            WHERE token <> '' AND LOWER(p.name_ar) LIKE '%' || LOWER(token) || '%'
          ) THEN 1
          WHEN EXISTS (
            SELECT 1 FROM unnest(string_to_array($${searchParamIdx}, ' ')) AS token
            WHERE token <> '' AND LOWER(COALESCE(p.name_en, '')) LIKE '%' || LOWER(token) || '%'
          ) THEN 2
          ELSE 3
        END),
        p.sort_order DESC,
        p.name_ar ASC
      `;
    }

    // Get products
    const dataParams = [...params, limit, offset];
    const result = await query(
      `SELECT p.id, p.category_id, p.name_ar, p.name_en, p.sku,
              p.description, p.description_en,
              p.image_url, p.images,
              p.price::float as price, p.discount_price::float as discount_price,
              p.stock_qty, p.is_active,
              p.track_stock, p.sort_order, p.source,
              p.vendor_id,
              v.slug as vendor_slug, v.name_ar as vendor_name,
              c.id as category_id_ref, c.name_ar as category_name, c.slug as category_slug, c.icon_url as category_icon,
              -- Aggregate rating from product_reviews so product cards can
              -- show a single star + count without a second round-trip.
              -- COALESCE keeps products with no reviews at 0 / 0 so the
              -- client can render the "no reviews yet" state.
              COALESCE(r.avg_rating, 0)::float as avg_rating,
              COALESCE(r.reviews_count, 0)::int as reviews_count,
              -- Active offer columns from the products_unified_with_offers view.
              p.active_offer_id, p.active_offer_title_ar, p.active_offer_type,
              p.active_offer_value::float as active_offer_value,
              p.active_offer_max_discount::float as active_offer_max_discount,
              p.active_offer_min_order::float as active_offer_min_order,
              p.active_offer_starts_at, p.active_offer_ends_at
       FROM products_unified_with_offers p
       LEFT JOIN categories c ON p.category_id = c.id
       LEFT JOIN vendors v ON v.id = p.vendor_id AND v.is_active = TRUE
       LEFT JOIN (
         SELECT product_id,
                AVG(rating)::numeric(3,2) as avg_rating,
                COUNT(*) as reviews_count
           FROM product_reviews
          WHERE is_approved = true
          GROUP BY product_id
       ) r ON r.product_id = p.id
       ${whereSQL}
       ORDER BY ${orderSQL}
       LIMIT $${dataParams.length - 1} OFFSET $${dataParams.length}`,
      dataParams
    );

    // Convert types properly and build clean response
    const products = result.rows.map((row: ProductRow) => {
      const listPrice = typeof row.price === 'number' ? row.price : (parseFloat(String(row.price)) || 0);
      const legacySale = row.discount_price != null
        ? (typeof row.discount_price === 'number' ? row.discount_price : parseFloat(String(row.discount_price)))
        : null;

      // Slice 5: hydrate `active_offer` and compute `effective_price`.
      let activeOffer = null;
      let offerEffective = listPrice;
      if (row.active_offer_id) {
        const value = typeof row.active_offer_value === 'number'
          ? row.active_offer_value
          : parseFloat(String(row.active_offer_value ?? 0));
        const maxDiscount = row.active_offer_max_discount != null
          ? (typeof row.active_offer_max_discount === 'number'
              ? row.active_offer_max_discount
              : parseFloat(String(row.active_offer_max_discount)))
          : null;
        const minOrder = row.active_offer_min_order != null
          ? (typeof row.active_offer_min_order === 'number'
              ? row.active_offer_min_order
              : parseFloat(String(row.active_offer_min_order)))
          : null;
        let rawSavings: number;
        if (row.active_offer_type === 'percentage') {
          rawSavings = (listPrice * value) / 100;
          if (maxDiscount != null) rawSavings = Math.min(rawSavings, maxDiscount);
        } else {
          rawSavings = Math.min(value, listPrice);
        }
        const savings = Math.min(Math.max(rawSavings, 0), listPrice);
        offerEffective = r2(listPrice - savings);
        activeOffer = {
          offer_id: row.active_offer_id,
          title_ar: row.active_offer_title_ar ?? '',
          discount_type: row.active_offer_type,
          discount_value: value,
          max_discount: maxDiscount,
          min_order: minOrder,
          starts_at: row.active_offer_starts_at ?? '',
          ends_at: row.active_offer_ends_at ?? '',
        };
      }

      // Effective price = min(offerEffective, legacySale, listPrice) when applicable.
      let effectivePrice = listPrice;
      if (offerEffective < listPrice) effectivePrice = offerEffective;
      if (legacySale != null && legacySale < listPrice && legacySale < effectivePrice) {
        effectivePrice = legacySale;
      }

      return {
        id: row.id,
        category_id: row.category_id,
        name_ar: row.name_ar,
        name_en: row.name_en,
        sku: row.sku,
        description: row.description,
        description_en: row.description_en,
        image_url: row.image_url,
        images: row.images || [],
        price: listPrice,
        discount_price: legacySale,
        stock_qty: typeof row.stock_qty === 'number' ? row.stock_qty : (parseInt(String(row.stock_qty)) || 0),
        is_active: row.is_active,
        track_stock: row.track_stock,
        sort_order: row.sort_order,
        source: row.source,
        vendor_id: row.vendor_id,
        vendor_slug: row.vendor_slug,
        vendor_name: row.vendor_name,
        category_name: row.category_name,
        category_slug: row.category_slug,
        category_icon: row.category_icon,
        avg_rating: typeof row.avg_rating === 'number' ? row.avg_rating : (parseFloat(String(row.avg_rating ?? 0)) || 0),
        reviews_count: typeof row.reviews_count === 'number' ? row.reviews_count : (parseInt(String(row.reviews_count ?? 0)) || 0),
        // Slice 5 — Offers
        active_offer: activeOffer,
        effective_price: effectivePrice < listPrice ? effectivePrice : null,
      };
    });

    const pagination = { page, limit, total, totalPages: Math.ceil(total / limit) };
    const wantMarkdown = acceptsMarkdown(request);

    // Return markdown if requested
    if (wantMarkdown) {
      const markdown = productsToMarkdown(products, pagination);
      return new NextResponse(markdown, {
        headers: {
          'Content-Type': 'text/markdown; charset=utf-8',
          'X-Markdown-Negotiation': 'enabled',
          'Cache-Control': 'public, max-age=300',
          'Content-Signal': 'ai-train=no, search=yes, ai-input=yes',
          'Vary': 'Accept',
        },
      });
    }

    // Default JSON response
    return NextResponse.json({
      success: true,
      data: products,
      pagination
    }, {
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
        'Cache-Control': 'public, max-age=300, stale-while-revalidate=600',
        'Content-Signal': 'ai-train=no, search=yes, ai-input=yes',
        'Vary': 'Accept',
      },
    });
  } catch (error) {
    logError('Error fetching products:', error);
    return NextResponse.json({ success: false, error: 'Failed to fetch products' }, { status: 500 });
  }
}
