-- 043_category_product_images.sql
-- Replaces Material-icon keys and external Unsplash URLs in categories.icon_url
-- with a real product image drawn from each category's own catalogue.
--
-- Generated by scripts/pick-category-images.mjs — re-run that script to
-- regenerate. Keyed by slug (not id) so it survives a category reseed, and
-- guarded by an inequality check so re-running is a no-op.

BEGIN;

-- اخرى <- سفرة نورا مقاس 120×120 (subtree-match)
UPDATE categories SET icon_url = '/images/products/8656fb69fd85.jpg'
 WHERE slug = 'اخرى' AND icon_url IS DISTINCT FROM '/images/products/8656fb69fd85.jpg';

-- البرجر <- برجر الدجاج ساديا 1كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/c9b4b8388b3b.jpg'
 WHERE slug = 'البرجر' AND icon_url IS DISTINCT FROM '/images/products/c9b4b8388b3b.jpg';

-- البهارات <- بهارات الركن اليمني بهارات المندي 200 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/75e606148869.jpg'
 WHERE slug = 'البهارات' AND icon_url IS DISTINCT FROM '/images/products/75e606148869.jpg';

-- الخضروات والفواكه <- طماطم صغير علبة (subtree-match)
UPDATE categories SET icon_url = '/images/products/61b7aea069c2.jpg'
 WHERE slug = 'الخضروات-والفواكه' AND icon_url IS DISTINCT FROM '/images/products/61b7aea069c2.jpg';

-- القهوة <- هيلز بروس قهوه امريكيه (name-match)
UPDATE categories SET icon_url = '/images/products/4651894de01c.jpg'
 WHERE slug = 'القهوة' AND icon_url IS DISTINCT FROM '/images/products/4651894de01c.jpg';

-- جبنة سائلة <- جبن بوك الاصلي سائل 130 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/da9968392d01.jpg'
 WHERE slug = 'جبنة-سائلة' AND icon_url IS DISTINCT FROM '/images/products/da9968392d01.jpg';

-- حفائض الاطفال <- حفائض اطفال بكوكا رقم ثلاثه 36 قطعه وسط (name-match)
UPDATE categories SET icon_url = '/images/products/bd2ed0f3c21c.jpg'
 WHERE slug = 'حفائض-الاطفال' AND icon_url IS DISTINCT FROM '/images/products/bd2ed0f3c21c.jpg';

-- خضروات <- فلفل شقراء احمر 1 كيلو (subtree-match)
UPDATE categories SET icon_url = '/images/products/75006bf5f969.jpg'
 WHERE slug = 'خضروات' AND icon_url IS DISTINCT FROM '/images/products/75006bf5f969.jpg';

-- دجاج مفروم <- دجاج مفروم انتاج 500 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/33fb167fadf3.jpg'
 WHERE slug = 'دجاج-مفروم' AND icon_url IS DISTINCT FROM '/images/products/33fb167fadf3.jpg';

-- رقائق البطاطس <- نادك كراكلز رقائق بطاطس الكاتشب 155جرام (name-match)
UPDATE categories SET icon_url = '/images/products/6a4ca8bbd439.jpg'
 WHERE slug = 'رقائق-البطاطس' AND icon_url IS DISTINCT FROM '/images/products/6a4ca8bbd439.jpg';

-- زبادي يوناني <- زبادي يوناني الصافي توت مشكل 3 × 150 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/ded4db7f7316.jpg'
 WHERE slug = 'زبادي-يوناني' AND icon_url IS DISTINCT FROM '/images/products/ded4db7f7316.jpg';

-- صدور الدجاج <- صدور دجاج داري 2 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/8f355403b1db.jpg'
 WHERE slug = 'صدور-الدجاج' AND icon_url IS DISTINCT FROM '/images/products/8f355403b1db.jpg';

-- صوصات السلطة <- صلصة سلطة سيزر من هاينز – 400 مل (name-match)
UPDATE categories SET icon_url = '/images/products/f5a8f97b9296.jpg'
 WHERE slug = 'صوصات-السلطة' AND icon_url IS DISTINCT FROM '/images/products/f5a8f97b9296.jpg';

-- علك <- علك غندور علبه بطيخ (name-match)
UPDATE categories SET icon_url = '/images/products/af316a03aa0a.jpg'
 WHERE slug = 'علك' AND icon_url IS DISTINCT FROM '/images/products/af316a03aa0a.jpg';

-- عيدان البطاطس <- بطاطس عيدان اكس 53 جرام حار خفيف (name-match)
UPDATE categories SET icon_url = '/images/products/acb708376d8d.jpg'
 WHERE slug = 'عيدان-البطاطس' AND icon_url IS DISTINCT FROM '/images/products/acb708376d8d.jpg';

-- قشطة <- قشطة التاج بالفراولة 95 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/309991fbce34.jpg'
 WHERE slug = 'قشطة' AND icon_url IS DISTINCT FROM '/images/products/309991fbce34.jpg';

-- كوكيز <- تيفاني كوكيز شوكولاتة 43 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/16e43165bb72.jpg'
 WHERE slug = 'كوكيز' AND icon_url IS DISTINCT FROM '/images/products/16e43165bb72.jpg';

-- لحم مفروم <- لحم غنم مفروم الذوق 400 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/999ee2e35df7.jpg'
 WHERE slug = 'لحم-مفروم' AND icon_url IS DISTINCT FROM '/images/products/999ee2e35df7.jpg';

-- مجمد جاهز للطهي <- كباب بقري نيكسو 1 كيلو (subtree-match)
UPDATE categories SET icon_url = '/images/products/d143be49a378.jpg'
 WHERE slug = 'مجمد-جاهز-للطهي' AND icon_url IS DISTINCT FROM '/images/products/d143be49a378.jpg';

-- مخبوزات سيتي <- ساندوتش تونه بابا خباز (subtree-match)
UPDATE categories SET icon_url = '/images/products/b231407ce8cc.jpg'
 WHERE slug = 'city-bakery' AND icon_url IS DISTINCT FROM '/images/products/b231407ce8cc.jpg';

-- مستلزمات الجسم <- صابون هيله للجسم مسك كاندي 100 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/b43d3d401503.jpg'
 WHERE slug = 'مستلزمات-الجسم' AND icon_url IS DISTINCT FROM '/images/products/b43d3d401503.jpg';

-- مسحوق غسيل الملابس <- موبي مسحوق غسيل الملابس 10 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/1cb67dec9673.jpg'
 WHERE slug = 'مسحوق-غسيل-الملابس' AND icon_url IS DISTINCT FROM '/images/products/1cb67dec9673.jpg';

-- معمول <- معمول حمدان 20 حبه بالقهوه التمر (name-match)
UPDATE categories SET icon_url = '/images/products/cada59f893d8.jpg'
 WHERE slug = 'معمول' AND icon_url IS DISTINCT FROM '/images/products/cada59f893d8.jpg';

-- منظفات متعددة الاستخدامات <- منظف متعدد الاستخدام جيف 470 مل (name-match)
UPDATE categories SET icon_url = '/images/products/a9f03b0641ce.jpg'
 WHERE slug = 'منظفات-متعددة-الاستخدامات' AND icon_url IS DISTINCT FROM '/images/products/a9f03b0641ce.jpg';

-- ورقيات <- كزبرة 1 ربطة (subtree-match)
UPDATE categories SET icon_url = '/images/products/094531a9d403.jpg'
 WHERE slug = 'ورقيات' AND icon_url IS DISTINCT FROM '/images/products/094531a9d403.jpg';

-- العصائر <- عصير ندى ليمون مع نعناع 1.3 لتر (subtree-match)
UPDATE categories SET icon_url = '/images/products/b05ff7d855dd.jpg'
 WHERE slug = 'العصائر' AND icon_url IS DISTINCT FROM '/images/products/b05ff7d855dd.jpg';

-- اللحوم والدواجن <- دجاج اليوم مبرد 1400 جرام (curated)
UPDATE categories SET icon_url = '/images/products/6af50d77e50d.jpg'
 WHERE slug = 'اللحوم-والدواجن' AND icon_url IS DISTINCT FROM '/images/products/6af50d77e50d.jpg';

-- بطاطس مجمدة <- بطاطس مجمده كابري 1 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/83a98f895b7a.jpg'
 WHERE slug = 'بطاطس-مجمدة' AND icon_url IS DISTINCT FROM '/images/products/83a98f895b7a.jpg';

-- بقوليات معلبة <- قول خلطه المصري 450 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/163ba68d51e7.jpg'
 WHERE slug = 'بقوليات-معلبة' AND icon_url IS DISTINCT FROM '/images/products/163ba68d51e7.jpg';

-- جبن <- جبنة كيري كريمة طازجة وحليب 400 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/3f902ff38a76.jpg'
 WHERE slug = 'جبن' AND icon_url IS DISTINCT FROM '/images/products/3f902ff38a76.jpg';

-- جبنة مكعبات <- جبنه كيري شده 5 قطع (name-match)
UPDATE categories SET icon_url = '/images/products/1ef8cf49ea39.jpg'
 WHERE slug = 'جبنة-مكعبات' AND icon_url IS DISTINCT FROM '/images/products/1ef8cf49ea39.jpg';

-- حلوى <- حلوى جلي كارز بورقات 10 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/2787b5812f37.jpg'
 WHERE slug = 'حلوى' AND icon_url IS DISTINCT FROM '/images/products/2787b5812f37.jpg';

-- خبز  - صامولي <- خبز برجر ساده مخابز النجاح 390 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/bc7e3beebff4.jpg'
 WHERE slug = 'خبز----صامولي' AND icon_url IS DISTINCT FROM '/images/products/bc7e3beebff4.jpg';

-- دجاج مبرد كامل <- دجاج اليوم مبرد 1300 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/e82f4b99c3b6.jpg'
 WHERE slug = 'chilled-chicken' AND icon_url IS DISTINCT FROM '/images/products/e82f4b99c3b6.jpg';

-- زبادي منكه <- زبادي اكتيفيا فطور عالماشي ١٥٠ جرام (name-match)
UPDATE categories SET icon_url = '/images/products/f460eb097cdf.jpg'
 WHERE slug = 'زبادي-منكه' AND icon_url IS DISTINCT FROM '/images/products/f460eb097cdf.jpg';

-- سائل غسيل الملابس <- سائل غسيل ملابس ملونة الوزير 1.5 لتر (name-match)
UPDATE categories SET icon_url = '/images/products/79e223293fd8.jpg'
 WHERE slug = 'سائل-غسيل-الملابس' AND icon_url IS DISTINCT FROM '/images/products/79e223293fd8.jpg';

-- شاورما الدجاج <- شاورما دجاج رويال 500 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/1c0bb562b7f3.jpg'
 WHERE slug = 'شاورما-الدجاج' AND icon_url IS DISTINCT FROM '/images/products/1c0bb562b7f3.jpg';

-- صوصات حلى <- ايلو جود فرنس تكساس برجر صوص - 200 جم (name-match)
UPDATE categories SET icon_url = '/images/products/a1b96f6d2243.jpg'
 WHERE slug = 'صوصات-حلى' AND icon_url IS DISTINCT FROM '/images/products/a1b96f6d2243.jpg';

-- فحم <- فحم طيبه 40 قرص (name-match)
UPDATE categories SET icon_url = '/images/products/eaedbbeae55f.jpg'
 WHERE slug = 'فحم' AND icon_url IS DISTINCT FROM '/images/products/eaedbbeae55f.jpg';

-- فطائر <- فطائر زعتر مروج 80 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/6599c2fe65e9.jpg'
 WHERE slug = 'فطائر' AND icon_url IS DISTINCT FROM '/images/products/6599c2fe65e9.jpg';

-- فواكه طازجة <- تفاح أخضر صحن (subtree-match)
UPDATE categories SET icon_url = '/images/products/887309bb1297.jpg'
 WHERE slug = 'fresh-fruits' AND icon_url IS DISTINCT FROM '/images/products/887309bb1297.jpg';

-- مرتديلا ونقانق <- نقانق دجاج كواليكو 340 ج 3 حبات (name-match)
UPDATE categories SET icon_url = '/images/products/cdb238035771.jpg'
 WHERE slug = 'مرتديلا-ونقانق' AND icon_url IS DISTINCT FROM '/images/products/cdb238035771.jpg';

-- مستلزمات الشعر <- مثبت شعر اولترا هولد 90 مل (name-match)
UPDATE categories SET icon_url = '/images/products/a74d0b44081c.jpg'
 WHERE slug = 'مستلزمات-الشعر' AND icon_url IS DISTINCT FROM '/images/products/a74d0b44081c.jpg';

-- مناديل <- مناديل كوفي ناعمه 8 × 600 منديل (name-match)
UPDATE categories SET icon_url = '/images/products/f90d47e4d28e.jpg'
 WHERE slug = 'tissues' AND icon_url IS DISTINCT FROM '/images/products/f90d47e4d28e.jpg';

-- هريس أغذية الأطفال <- سيريلاك حليب أرز 400 جرام (subtree-match)
UPDATE categories SET icon_url = '/images/products/5e67db04eb8e.jpg'
 WHERE slug = 'هريس-أغذية-الأطفال' AND icon_url IS DISTINCT FROM '/images/products/5e67db04eb8e.jpg';

-- ارجل الدجاج <- ارجل الدجاج الوطنيه 450 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/e961c3c1b18f.jpg'
 WHERE slug = 'ارجل-الدجاج' AND icon_url IS DISTINCT FROM '/images/products/e961c3c1b18f.jpg';

-- الألبان والأجبان <- لبن اكتيفيا كفير 280 ملي (name-match)
UPDATE categories SET icon_url = '/images/products/1fa23db27ba2.jpg'
 WHERE slug = 'الالبان-والاجبان' AND icon_url IS DISTINCT FROM '/images/products/1fa23db27ba2.jpg';

-- بسكويت <- بسكويت اني تايم مارشميلو28 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/d0efcca84375.jpg'
 WHERE slug = 'biscuits' AND icon_url IS DISTINCT FROM '/images/products/d0efcca84375.jpg';

-- تورتيلا <- لفائف تورتيلا فونتي الحارة 250 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/5cadf5e2ec36.jpg'
 WHERE slug = 'تورتيلا' AND icon_url IS DISTINCT FROM '/images/products/5cadf5e2ec36.jpg';

-- جبن مبشور <- جبن موزاريلا مبشوره 1 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/b54e28c92e51.jpg'
 WHERE slug = 'جبن-مبشور' AND icon_url IS DISTINCT FROM '/images/products/b54e28c92e51.jpg';

-- حليب مجفف <- حليب مجفف ابو قوس الاصلي 170 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/3743221eb917.jpg'
 WHERE slug = 'حليب-مجفف' AND icon_url IS DISTINCT FROM '/images/products/3743221eb917.jpg';

-- شاي الأعشاب <- شاي اعشاب كمون (name-match)
UPDATE categories SET icon_url = '/images/products/aef4b3144396.jpg'
 WHERE slug = 'شاي-الأعشاب' AND icon_url IS DISTINCT FROM '/images/products/aef4b3144396.jpg';

-- صابون غسل المواعين <- فيري صابون غسيل 600 مل (name-match)
UPDATE categories SET icon_url = '/images/products/81dffabe859b.jpg'
 WHERE slug = 'صابون-غسل-المواعين' AND icon_url IS DISTINCT FROM '/images/products/81dffabe859b.jpg';

-- صوصات الطبخ <- صوص الراقي بديل دبس الرمان 700 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/5d17c66d2e39.jpg'
 WHERE slug = 'صوصات-الطبخ' AND icon_url IS DISTINCT FROM '/images/products/5d17c66d2e39.jpg';

-- عناية اليدين <- سائل غسيل اليدين سنروزا 300 مل ليلك (name-match)
UPDATE categories SET icon_url = '/images/products/31f792152624.jpg'
 WHERE slug = 'عناية-اليدين' AND icon_url IS DISTINCT FROM '/images/products/31f792152624.jpg';

-- فواكه مجمدة <- جوافه مجمده فروتيتو 1 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/d9423510723f.jpg'
 WHERE slug = 'فواكه-مجمدة' AND icon_url IS DISTINCT FROM '/images/products/d9423510723f.jpg';

-- كاس وعلب <- مزيج توت الاساي والموز 500 جرام (subtree-match)
UPDATE categories SET icon_url = '/images/products/06a8abaab0b7.jpg'
 WHERE slug = 'كاس-وعلب' AND icon_url IS DISTINCT FROM '/images/products/06a8abaab0b7.jpg';

-- لحوم طازجة <- لحم عجل بدون عظم 1 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/136a6d88d2e2.jpg'
 WHERE slug = 'لحوم-طازجة' AND icon_url IS DISTINCT FROM '/images/products/136a6d88d2e2.jpg';

-- معجنات مجمدة <- فطير مشلتت سنبله 400 جرام (subtree-match)
UPDATE categories SET icon_url = '/images/products/bf7c73fa9383.jpg'
 WHERE slug = 'معجنات-مجمدة' AND icon_url IS DISTINCT FROM '/images/products/bf7c73fa9383.jpg';

-- أدوات للمطبخ <- أطباق أبو سهم 50 حبة مقاس 242 (subtree-match)
UPDATE categories SET icon_url = '/images/products/227a773ebe45.jpg'
 WHERE slug = 'أدوات-للمطبخ' AND icon_url IS DISTINCT FROM '/images/products/227a773ebe45.jpg';

-- الأطعمة المجمدة <- امريكانا - زنجز ستربس الدجاج حار ومقرمش 320جم (name-match)
UPDATE categories SET icon_url = '/images/products/beab24f2b888.jpg'
 WHERE slug = 'الأطعمة-المجمدة' AND icon_url IS DISTINCT FROM '/images/products/beab24f2b888.jpg';

-- الشاي الأسود <- شاي الكبوس شاي أسود فاخر 454 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/87b235e45ca0.jpg'
 WHERE slug = 'الشاي-الأسود' AND icon_url IS DISTINCT FROM '/images/products/87b235e45ca0.jpg';

-- الشوكولاتة <- شوكولاته رنا ميرو 16 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/04ca0f5cc5ef.jpg'
 WHERE slug = 'الشوكولاتة' AND icon_url IS DISTINCT FROM '/images/products/04ca0f5cc5ef.jpg';

-- توست <- توست هرفي ابيض 600 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/ebaf5a9e9bc6.jpg'
 WHERE slug = 'توست' AND icon_url IS DISTINCT FROM '/images/products/ebaf5a9e9bc6.jpg';

-- جبنة شرائح <- شرائح شيدر فرسانا 170 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/7b7d5e353559.jpg'
 WHERE slug = 'جبنة-شرائح' AND icon_url IS DISTINCT FROM '/images/products/7b7d5e353559.jpg';

-- حليب منكه <- حليب منكه الكراميل المملح نادك - 225 (name-match)
UPDATE categories SET icon_url = '/images/products/6c1f1c958dd3.jpg'
 WHERE slug = 'حليب-منكه' AND icon_url IS DISTINCT FROM '/images/products/6c1f1c958dd3.jpg';

-- خضروات مجمدة <- ملوخيه حياه مجمده 400 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/12183fcf1bc8.jpg'
 WHERE slug = 'خضروات-مجمدة' AND icon_url IS DISTINCT FROM '/images/products/12183fcf1bc8.jpg';

-- زيت الزيتون <- زيت زيتون خليط زيت متبقي 800 مل (name-match)
UPDATE categories SET icon_url = '/images/products/24271b277f3d.jpg'
 WHERE slug = 'زيت-الزيتون' AND icon_url IS DISTINCT FROM '/images/products/24271b277f3d.jpg';

-- فواكه معلبة <- خوخ انصاف اكوادور 400 جرام (subtree-match)
UPDATE categories SET icon_url = '/images/products/7afafeece552.jpg'
 WHERE slug = 'فواكه-معلبة' AND icon_url IS DISTINCT FROM '/images/products/7afafeece552.jpg';

-- مزيل العرق <- بخاخ مزيل عرق فوج فورنس 150 مل (name-match)
UPDATE categories SET icon_url = '/images/products/e9625bef5660.jpg'
 WHERE slug = 'مزيل-العرق' AND icon_url IS DISTINCT FROM '/images/products/e9625bef5660.jpg';

-- المخبوزات <- خبز جرجر بطاطس النجاح 402 جرام (subtree-match)
UPDATE categories SET icon_url = '/images/products/abfd16086a7c.jpg'
 WHERE slug = 'المخبوزات' AND icon_url IS DISTINCT FROM '/images/products/abfd16086a7c.jpg';

-- المعكرونة <- معكرونه المائده 4 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/b3c531fcd1d5.jpg'
 WHERE slug = 'المعكرونة' AND icon_url IS DISTINCT FROM '/images/products/b3c531fcd1d5.jpg';

-- حليب مبخر <- بوني حليب مبخر كامل الدسم 170 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/c85a4d6844ea.jpg'
 WHERE slug = 'حليب-مبخر' AND icon_url IS DISTINCT FROM '/images/products/c85a4d6844ea.jpg';

-- دجاج مجمد <- كرتون دجاج مجمد الوطنية 600 جرام 10 حبات (name-match)
UPDATE categories SET icon_url = '/images/products/917fe6756eb6.jpg'
 WHERE slug = 'frozen-chicken' AND icon_url IS DISTINCT FROM '/images/products/917fe6756eb6.jpg';

-- شابورة <- شابوره مروج كيك ناشف 300 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/6fe39dd965ea.jpg'
 WHERE slug = 'شابورة' AND icon_url IS DISTINCT FROM '/images/products/6fe39dd965ea.jpg';

-- كيك <- كيك تمر كيكنا 15 قطعه (name-match)
UPDATE categories SET icon_url = '/images/products/0da2568ccff3.jpg'
 WHERE slug = 'كيك' AND icon_url IS DISTINCT FROM '/images/products/0da2568ccff3.jpg';

-- مستلزمات الوجه <- مقشر وجه اكستر اكليل الجبل 400 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/767b6e6313a0.jpg'
 WHERE slug = 'مستلزمات-الوجه' AND icon_url IS DISTINCT FROM '/images/products/767b6e6313a0.jpg';

-- مشروبات غازية <- مشروب غازي جيمي حمضيات 240 مل (name-match)
UPDATE categories SET icon_url = '/images/products/df436bcedc7a.jpg'
 WHERE slug = 'soft-drinks' AND icon_url IS DISTINCT FROM '/images/products/df436bcedc7a.jpg';

-- منعم الاقمشة <- منعم الأقمشة كومفورت برائحة ندى الربيع 4  لتر (name-match)
UPDATE categories SET icon_url = '/images/products/9d7413bb1815.jpg'
 WHERE slug = 'منعم-الاقمشة' AND icon_url IS DISTINCT FROM '/images/products/9d7413bb1815.jpg';

-- المقاضي <- سكر الاسره 10 كجم (curated)
UPDATE categories SET icon_url = '/images/products/35ca358d826b.jpg'
 WHERE slug = 'المقاضي' AND icon_url IS DISTINCT FROM '/images/products/35ca358d826b.jpg';

-- بحريات مجمد <- السمك فيليه امبرور مجمد 1 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/b042014ef54b.jpg'
 WHERE slug = 'بحريات-مجمد' AND icon_url IS DISTINCT FROM '/images/products/b042014ef54b.jpg';

-- حلويات العيد <- اكياس توزيعات العيد (name-match)
UPDATE categories SET icon_url = '/images/products/38d8315a943e.jpg'
 WHERE slug = 'حلويات-العيد' AND icon_url IS DISTINCT FROM '/images/products/38d8315a943e.jpg';

-- حليب الثلاجة <- حليب الصافي طازج كامل الدسم ٨٥٠ ملي (name-match)
UPDATE categories SET icon_url = '/images/products/a01bf6c90d21.jpg'
 WHERE slug = 'حليب-الثلاجة' AND icon_url IS DISTINCT FROM '/images/products/a01bf6c90d21.jpg';

-- شامبو العباية <- شامبو العبايات العجيب 1 لتر (name-match)
UPDATE categories SET icon_url = '/images/products/ddbfb524ab99.jpg'
 WHERE slug = 'شامبو-العباية' AND icon_url IS DISTINCT FROM '/images/products/ddbfb524ab99.jpg';

-- عصير مركز <- عصير تانج تروبيكال 2 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/c2828a2465d3.jpg'
 WHERE slug = 'عصير-مركز' AND icon_url IS DISTINCT FROM '/images/products/c2828a2465d3.jpg';

-- معطرات الجو <- معطر جو مركز فورزان 125 مل (name-match)
UPDATE categories SET icon_url = '/images/products/8edc5d11d41d.jpg'
 WHERE slug = 'معطرات-الجو' AND icon_url IS DISTINCT FROM '/images/products/8edc5d11d41d.jpg';

-- مكسرات <- مكسرات فيرفا مشكل 250 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/e3b16e89e91b.jpg'
 WHERE slug = 'nuts' AND icon_url IS DISTINCT FROM '/images/products/e3b16e89e91b.jpg';

-- السناكات والحلويات <- ويفر كات كات 12 × 24 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/4e47018e420d.jpg'
 WHERE slug = 'السناكات-والحلويات' AND icon_url IS DISTINCT FROM '/images/products/4e47018e420d.jpg';

-- الشاي الأخضر <- شاي اخضر للتنحيف 10 اظرف (name-match)
UPDATE categories SET icon_url = '/images/products/7b2aff8c4b3b.jpg'
 WHERE slug = 'الشاي-الأخضر' AND icon_url IS DISTINCT FROM '/images/products/7b2aff8c4b3b.jpg';

-- تونة <- تونه الريان 100 ج (name-match)
UPDATE categories SET icon_url = '/images/products/8e234e211a52.jpg'
 WHERE slug = 'تونة' AND icon_url IS DISTINCT FROM '/images/products/8e234e211a52.jpg';

-- سمبوسة <- سمبوسه عجينه ارياف 400 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/4db7fff42d8f.jpg'
 WHERE slug = 'سمبوسة' AND icon_url IS DISTINCT FROM '/images/products/4db7fff42d8f.jpg';

-- كريمة طبخ <- كريمه الطبخ الري 1 لتر (name-match)
UPDATE categories SET icon_url = '/images/products/6f68bd0b9159.jpg'
 WHERE slug = 'كريمة-طبخ' AND icon_url IS DISTINCT FROM '/images/products/6f68bd0b9159.jpg';

-- مبيد حشرات <- مبيد بوف باف 300 مل (name-match)
UPDATE categories SET icon_url = '/images/products/d868b972ac7b.jpg'
 WHERE slug = 'مبيد-حشرات' AND icon_url IS DISTINCT FROM '/images/products/d868b972ac7b.jpg';

-- مستلزمات الاسنان <- معجون اسنان كولجيت ازرق 100 مل (name-match)
UPDATE categories SET icon_url = '/images/products/185af6102590.jpg'
 WHERE slug = 'مستلزمات-الاسنان' AND icon_url IS DISTINCT FROM '/images/products/185af6102590.jpg';

-- المشروبات <- مشروب ليبتون فوق ايس تي 315 ملي (subtree-match)
UPDATE categories SET icon_url = '/images/products/ca2763891764.jpg'
 WHERE slug = 'المشروبات' AND icon_url IS DISTINCT FROM '/images/products/ca2763891764.jpg';

-- حليب مكثف <- حليب مكثف نستله الاصلي 370 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/eda5f57e8e39.jpg'
 WHERE slug = 'حليب-مكثف' AND icon_url IS DISTINCT FROM '/images/products/eda5f57e8e39.jpg';

-- خليط كيك <- خليط كيك كوينز شوكولاته 500 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/b07371c3b841.jpg'
 WHERE slug = 'خليط-كيك' AND icon_url IS DISTINCT FROM '/images/products/b07371c3b841.jpg';

-- زيت الطبخ <- زيت رياده للطبخ 750 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/f72d0feeaee7.jpg'
 WHERE slug = 'زيت-الطبخ' AND icon_url IS DISTINCT FROM '/images/products/f72d0feeaee7.jpg';

-- عناية الاطفال <- شامبو للاطفال جيرسي 400 مل (name-match)
UPDATE categories SET icon_url = '/images/products/cbc1e74cd031.jpg'
 WHERE slug = 'عناية-الاطفال' AND icon_url IS DISTINCT FROM '/images/products/cbc1e74cd031.jpg';

-- مشروبات الشعير <- شراب شعير بربيكان - بنكهه الشعير 330مل (name-match)
UPDATE categories SET icon_url = '/images/products/2831fc9c43cd.jpg'
 WHERE slug = 'مشروبات-الشعير' AND icon_url IS DISTINCT FROM '/images/products/2831fc9c43cd.jpg';

-- الأرز <- ارز الارز كلاسيكي 10 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/42465267eb6a.jpg'
 WHERE slug = 'الأرز' AND icon_url IS DISTINCT FROM '/images/products/42465267eb6a.jpg';

-- العناية بالمنزل <- معطر ملابس لورانس اصفر 1 لتر (subtree-match)
UPDATE categories SET icon_url = '/images/products/a537194f4d62.jpg'
 WHERE slug = 'العناية-بالمنزل' AND icon_url IS DISTINCT FROM '/images/products/a537194f4d62.jpg';

-- الفشار <- فشار البطل بنكهة الزبدة 90 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/a0b85d97234c.jpg'
 WHERE slug = 'الفشار' AND icon_url IS DISTINCT FROM '/images/products/a0b85d97234c.jpg';

-- زبادي <- زبادي الصافي 120 جم (name-match)
UPDATE categories SET icon_url = '/images/products/9445dad71a99.jpg'
 WHERE slug = 'زبادي' AND icon_url IS DISTINCT FROM '/images/products/9445dad71a99.jpg';

-- مزيل الشعر <- مزيل شعر فيت سيليكون 100 مل (name-match)
UPDATE categories SET icon_url = '/images/products/0ed9e48f7e2f.jpg'
 WHERE slug = 'مزيل-الشعر' AND icon_url IS DISTINCT FROM '/images/products/0ed9e48f7e2f.jpg';

-- مشروبات الطاقة <- مشروب طاقه بوم بوم 250 مل (name-match)
UPDATE categories SET icon_url = '/images/products/5056cf26999d.jpg'
 WHERE slug = 'مشروبات-الطاقة' AND icon_url IS DISTINCT FROM '/images/products/5056cf26999d.jpg';

-- جيلاتين <- جلي كنزانيا دب 140 جرام (subtree-match)
UPDATE categories SET icon_url = '/images/products/4df88487c869.jpg'
 WHERE slug = 'جيلاتين' AND icon_url IS DISTINCT FROM '/images/products/4df88487c869.jpg';

-- عصائر بدون سكر <- عصير شراب الفواكه المشكله بدون سكر المراعي 200 ملي (name-match)
UPDATE categories SET icon_url = '/images/products/37061ed51ba1.jpg'
 WHERE slug = 'عصائر-بدون-سكر' AND icon_url IS DISTINCT FROM '/images/products/37061ed51ba1.jpg';

-- كريمة خفق <- ويبي مزيج كريمة الخفق (name-match)
UPDATE categories SET icon_url = '/images/products/0659ca389344.jpg'
 WHERE slug = 'كريمة-خفق' AND icon_url IS DISTINCT FROM '/images/products/0659ca389344.jpg';

-- مستلزمات المرأة <- فوط نسائيه برايفت حجم كبير 26 (subtree-match)
UPDATE categories SET icon_url = '/images/products/1c9fd21b8f56.jpg'
 WHERE slug = 'مستلزمات-المرأة' AND icon_url IS DISTINCT FROM '/images/products/1c9fd21b8f56.jpg';

-- مستلزمات المنزل <- كاسات بلاستيك 200 كاس (subtree-match)
UPDATE categories SET icon_url = '/images/products/ed44751036b3.jpg'
 WHERE slug = 'مستلزمات-المنزل' AND icon_url IS DISTINCT FROM '/images/products/ed44751036b3.jpg';

-- معجون طماطم <- معجون طماطم معين 1 (name-match)
UPDATE categories SET icon_url = '/images/products/2f571206e9f0.jpg'
 WHERE slug = 'معجون-طماطم' AND icon_url IS DISTINCT FROM '/images/products/2f571206e9f0.jpg';

-- العناية الشخصية <- شامبو كلير للرجال عنايه فائقه 350 مل (subtree-match)
UPDATE categories SET icon_url = '/images/products/1c402e31646e.jpg'
 WHERE slug = 'العناية-الشخصية' AND icon_url IS DISTINCT FROM '/images/products/1c402e31646e.jpg';

-- المايونيز والخردل <- مايونيز بالفلفل اوركيد 300 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/f299fa1981fd.jpg'
 WHERE slug = 'المايونيز-والخردل' AND icon_url IS DISTINCT FROM '/images/products/f299fa1981fd.jpg';

-- لبنة <- لبنه طازجه كامله الدسم نادك 200 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/8ec2901dad99.jpg'
 WHERE slug = 'لبنة' AND icon_url IS DISTINCT FROM '/images/products/8ec2901dad99.jpg';

-- مستلزمات الحلاقة <- كريم حلاقه جيليت 70 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/e0dd7d2b8ce0.jpg'
 WHERE slug = 'مستلزمات-الحلاقة' AND icon_url IS DISTINCT FROM '/images/products/e0dd7d2b8ce0.jpg';

-- مياه  -200مل <- مياة عذاري 200 مل (name-match)
UPDATE categories SET icon_url = '/images/products/5ed92fa21554.jpg'
 WHERE slug = 'مياه' AND icon_url IS DISTINCT FROM '/images/products/5ed92fa21554.jpg';

-- حليب طويل الاجل <- حليب قليل الدسم في السعوديه 200 ملي (name-match)
UPDATE categories SET icon_url = '/images/products/8b607efa908a.jpg'
 WHERE slug = 'حليب-طويل-الاجل' AND icon_url IS DISTINCT FROM '/images/products/8b607efa908a.jpg';

-- زيتون وورق عنب <- ريم ورق عنب 1000 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/b702388e4663.jpg'
 WHERE slug = 'زيتون-وورق-عنب' AND icon_url IS DISTINCT FROM '/images/products/b702388e4663.jpg';

-- الشطة <- شطة جلوريا 4.7 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/c6d627db13c7.jpg'
 WHERE slug = 'الشطة' AND icon_url IS DISTINCT FROM '/images/products/c6d627db13c7.jpg';

-- زبدة <- زبده لوتس 400 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/5596f68e9c29.jpg'
 WHERE slug = 'زبدة' AND icon_url IS DISTINCT FROM '/images/products/5596f68e9c29.jpg';

-- حليب الاطفال <- الري حليب موز 18*125م (name-match)
UPDATE categories SET icon_url = '/images/products/87c45a5547d6.jpg'
 WHERE slug = 'حليب-الاطفال' AND icon_url IS DISTINCT FROM '/images/products/87c45a5547d6.jpg';

-- سكر وملح <- ملح ساسا 750 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/222687dbdf4b.jpg'
 WHERE slug = 'سكر-وملح' AND icon_url IS DISTINCT FROM '/images/products/222687dbdf4b.jpg';

-- السمن <- سمن نباتي كريستال 700 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/9bc737e5e179.jpg'
 WHERE slug = 'السمن' AND icon_url IS DISTINCT FROM '/images/products/9bc737e5e179.jpg';

-- معلبات اخرى <- مخلل خيار اهداب 1300 جرام (subtree-match)
UPDATE categories SET icon_url = '/images/products/bdd13963abef.jpg'
 WHERE slug = 'معلبات-اخرى' AND icon_url IS DISTINCT FROM '/images/products/bdd13963abef.jpg';

-- بيض <- بيض طبق (name-match)
UPDATE categories SET icon_url = '/images/products/26479584549d.jpg'
 WHERE slug = 'eggs' AND icon_url IS DISTINCT FROM '/images/products/26479584549d.jpg';

-- معلبات قابلة للدهن <- كريمة فستق قابلة للدهن 200 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/80b90f81d31d.jpg'
 WHERE slug = 'معلبات-قابلة-للدهن' AND icon_url IS DISTINCT FROM '/images/products/80b90f81d31d.jpg';

-- حلاوة طحينية <- حلاوة طحينية هالفة الكسيح 1 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/9e33a25d1b0d.jpg'
 WHERE slug = 'حلاوة-طحينية' AND icon_url IS DISTINCT FROM '/images/products/9e33a25d1b0d.jpg';

-- كاتشب <- كاتشب مواسم 340 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/c8a8521f519d.jpg'
 WHERE slug = 'كاتشب' AND icon_url IS DISTINCT FROM '/images/products/c8a8521f519d.jpg';

-- كورن فليكس <- كورن فليكس كلوجز 1 كيلو (name-match)
UPDATE categories SET icon_url = '/images/products/35a9a522bdde.jpg'
 WHERE slug = 'كورن-فليكس' AND icon_url IS DISTINCT FROM '/images/products/35a9a522bdde.jpg';

-- العسل <- عسل طبيعي المراعي 500 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/84681aeb5f63.jpg'
 WHERE slug = 'العسل' AND icon_url IS DISTINCT FROM '/images/products/84681aeb5f63.jpg';

-- بودرة <- كاكاو بودرة زينا 200 جم (name-match)
UPDATE categories SET icon_url = '/images/products/e7707921dc9a.jpg'
 WHERE slug = 'بودرة' AND icon_url IS DISTINCT FROM '/images/products/e7707921dc9a.jpg';

-- نودلز <- نودلز كاربونارا بولداك رامن حار 5×130 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/6b9fb4299994.jpg'
 WHERE slug = 'نودلز' AND icon_url IS DISTINCT FROM '/images/products/6b9fb4299994.jpg';

-- ذرة <- ذره حلوه جلوريا 340 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/637724fb9964.jpg'
 WHERE slug = 'ذرة' AND icon_url IS DISTINCT FROM '/images/products/637724fb9964.jpg';

-- فطر <- قطع فطر الريم 425 جرام (name-match)
UPDATE categories SET icon_url = '/images/products/7e8094792014.jpg'
 WHERE slug = 'فطر' AND icon_url IS DISTINCT FROM '/images/products/7e8094792014.jpg';

-- التمور <- تمر نبوت 1 كيلو (subtree-match)
UPDATE categories SET icon_url = '/images/products/623e049b6222.jpg'
 WHERE slug = 'التمور' AND icon_url IS DISTINCT FROM '/images/products/623e049b6222.jpg';

-- المعلبات <- طماطم مفرومة في عصير الطماطم من دل مونتي، 400 غرام (subtree-match)
UPDATE categories SET icon_url = '/images/products/3c090154f182.jpg'
 WHERE slug = 'المعلبات' AND icon_url IS DISTINCT FROM '/images/products/3c090154f182.jpg';

-- مواد غذائية <- كورن فليكس بنس 250 جرام (subtree-match)
UPDATE categories SET icon_url = '/images/products/2817844fa7af.jpg'
 WHERE slug = 'مواد-غذائية' AND icon_url IS DISTINCT FROM '/images/products/2817844fa7af.jpg';

COMMIT;
