-- 113 — PCP-147 — backfill 20 placeholder app_migrations checksums with
-- the real FNV-1a of the current file so the drift detector can do its job.
--
-- 20 of 121 rows in app_migrations have literal `manual*` placeholder
-- strings (length 6-14) that the runner's `existing !== fileCs` check
-- at scripts/migrate.ts:294 will never match — producing 20 permanent
-- false-positive "drift" rows. The dry-run output today is
--   [plan] 121 total — 135 applied, 0 pending, 121 already done in range, 90 drift
-- (PCP-137 territory from Phase 14, partially addressed by this fix).
--
-- Distribution of placeholders before this migration:
--   "manual"          (6 chars)  : 9 files
--   "manual:NNN"      (10 chars) : 6 files
--   "manual-apply"    (12 chars) : 3 files
--   "manual-applied"  (14 chars) : 2 files
--
-- All hashes below were generated by replicating the FNV-1a 64-bit function
-- from scripts/migrate.ts:201-211 (validated against the live row for
-- 018_order_tracking_code.sql which matches the stored 2929462028a8b42a).
--
-- Safety: only updates rows that currently have a placeholder
-- (LENGTH(checksum) < 16). Real FNV-1a rows (16 chars) and SHA-256 rows
-- (64 chars) are untouched.

BEGIN;

UPDATE app_migrations SET checksum = 'adf792ea8bf65cf1' WHERE filename = '016_guest_cart_unique_session_product.sql' AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '6a30f22ecb8c1587' WHERE filename = '036_products_unified_refresh.sql'           AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '3a8a622676fd9bed' WHERE filename = '037_vendor_aware_cart.sql'                  AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '6a467a101ec1c369' WHERE filename = '038_multi_vendor_checkout.sql'              AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '6c5f0bb43017c2c4' WHERE filename = '039_legacy_products_readonly.sql'           AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = 'c7ab481a0fc4a8b1' WHERE filename = '039b_vendor_products_legacy_columns.sql'    AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = 'fc2c482a7ab84f52' WHERE filename = '039c_products_unified_use_new_columns.sql'  AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '09f167c95c61ccd7' WHERE filename = '040_offers.sql'                            AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '699e9a97da5b3544' WHERE filename = '040b_products_unified_with_offers.sql'     AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '41e6435913f843f2' WHERE filename = '054_vendor_order_items_product_nullable.sql' AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '761562d37f95f49c' WHERE filename = '055_products_category_nullable.sql'        AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = 'd2afd145c5e6216b' WHERE filename = '069_backfill_drivers_admin_link.sql'       AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '7a2d30dc964a84cf' WHERE filename = '070_reconcile_products_to_vendor_products.sql' AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '02c15dd41648e6c6' WHERE filename = '071_phase2_indexes.sql'                   AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = 'f2d813391284d906' WHERE filename = '098_next_cache_host_permissions.sql'       AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '295113dea993e16a' WHERE filename = '099_drop_dead_rls_policies.sql'            AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '3e11a812a99afa51' WHERE filename = '100_products_readonly_allow_delete.sql'    AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '3bc28a826c8a377a' WHERE filename = '101_apply_missing_after_rebuild.sql'       AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = 'd44bb109f583382d' WHERE filename = '102_add_missing_fk_indexes.sql'            AND LENGTH(checksum) < 16;
UPDATE app_migrations SET checksum = '7bbd1a5d7b45299d' WHERE filename = '103_backfill_image_url.sql'                AND LENGTH(checksum) < 16;

-- Audit marker (Phase 14/15 convention from migrations 111/112).
-- _migration_guards PK column is `guard_name` (not `name`).
INSERT INTO _migration_guards (guard_name, active, created_at)
  VALUES ('pcp147_checksum_backfill', TRUE, NOW())
  ON CONFLICT (guard_name) DO UPDATE
    SET active = EXCLUDED.active,
        created_at = EXCLUDED.created_at;

COMMIT;
